
name: pytorch-env
dependencies:
  - python=3.11
  - pip
  - pip:
    - torch>=2.0.0
    - torchvision
    - pandas
    - numpy
    - scikit-learn
    - mlflow
    - joblib
    - azure-ai-ml
    - azureml-mlflow
channels:
  - conda-forge
  - pytorch
